<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * The house "maker" liquidity is regenerated every minute; old rows were only marked
     * cancelled, so spot_orders grew to millions and the open-orders query took ~2.6s.
     * Delete all maker rows (regenerated by spot:seed) and index the hot columns.
     */
    public function up(): void
    {
        // Prune in chunks so we don't lock the table / blow memory.
        do {
            $n = DB::table('spot_orders')->where('is_maker', true)->limit(10000)->delete();
        } while ($n > 0);

        // Also drop any leftover cancelled/filled house rows with no owner.
        do {
            $n = DB::table('spot_orders')->whereNull('user_id')->limit(10000)->delete();
        } while ($n > 0);

        Schema::table('spot_orders', function (Blueprint $table) {
            $table->index(['user_id', 'status'], 'spot_orders_user_status_idx');
            $table->index(['instrument_id', 'side', 'status'], 'spot_orders_inst_side_status_idx');
        });
    }

    public function down(): void
    {
        Schema::table('spot_orders', function (Blueprint $table) {
            $table->dropIndex('spot_orders_user_status_idx');
            $table->dropIndex('spot_orders_inst_side_status_idx');
        });
    }
};
